version: '3.8'

services:
  auth:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - .env


  profile:
    build: ./profile-service
    container_name: profile-service
    env_file:
      - .env



  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 for web traffic
    depends_on:
      - auth
      - profile
