version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            cd auth-service
            docker build -t my-node-app .
      - run:
          name: Run tests
          command: |
            docker run my-node-app npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
