version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            cd auth-service
            docker build -t my-node-app .


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
