name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up SSH for deployment
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        source: "./"
        target: "/home/${{ secrets.SERVER_USER }}/docker-app"  # Adjust path as needed
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy on Remote Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.SERVER_USER }}/docker-app
          # docker-compose pull  # Pull the latest images
          docker-compose down  # Stop existing containers
          docker-compose up -d --build # Start new containers in detached mode
